name = "FMIBuild"
uuid = "226f0e26-6dd6-4589-ada7-1d32f6e1d800"
authors = ["TT <tobias.thummerer@informatik.uni-augsburg.de>", "LM <lars.mikelsons@informatik.uni-augsburg.de>"]
version = "0.3.3"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
FMIBase = "900ee838-d029-460e-b485-d98a826ceef2"
PackageCompiler = "9b87118b-4619-50d2-8e1e-99f35a4d4d9d"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
Dates = "1"
FMIBase = "1.0.0"
PackageCompiler = "2.1.9, 2.2.0"
Pkg = "1"
julia = "1.6"